config/routes.rb
ResourceAllocation::Application.routes.draw do
  resources :technologies

  root to: "projects#index"
  resources :res_allocations
  resources :allocation_dates

  resources :projects 

  resources :resources
  match 'get_projects' => 'res_allocations#get_projects'
  match 'get_resources' => 'res_allocations#get_resources'
  match 'tags_autocomplete' => 'application#tags'
  match 'manage_tag' => 'projects#manage_tag'

end

app/models/res_allocation.rb
class ResAllocation < ActiveRecord::Base
  belongs_to :allocation_date
  belongs_to :project
  belongs_to :resource
  attr_accessible :hours, :allocation_date_id, :project_id, :resource_id
end

app/controllers/res_allocations_controller.rb
class ResAllocationsController < ApplicationController
  # GET /res_allocations
  # GET /res_allocations.json
  def index
    @allocation_date=AllocationDate.find params[:id]
    @res_allocations = @allocation_date.res_allocations

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @res_allocations }
    end
  end

  # GET /res_allocations/1
  # GET /res_allocations/1.json
  def show
    @res_allocation = ResAllocation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @res_allocation }
    end
  end

  # GET /res_allocations/new
  # GET /res_allocations/new.json
  def new
    @allocation_date=AllocationDate.find params[:date_id]
    @res_allocation = ResAllocation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @res_allocation }
    end
  end

  # GET /res_allocations/1/edit
  def edit
    @allocation_date=AllocationDate.find params[:date_id]
    @res_allocation = ResAllocation.find(params[:id])
  end

  # POST /res_allocations
  # POST /res_allocations.json
  def create
    @res_allocation = ResAllocation.new(params[:res_allocation])

    respond_to do |format|
      if @res_allocation.save
        format.html { redirect_to @res_allocation, notice: 'Res allocation was successfully created.' }
        format.json { render json: @res_allocation, status: :created, location: @res_allocation }
      else
        format.html { render action: "new" }
        format.json { render json: @res_allocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /res_allocations/1
  # PUT /res_allocations/1.json
  def update
    @res_allocation = ResAllocation.find(params[:id])

    respond_to do |format|
      if @res_allocation.update_attributes(params[:res_allocation])
        format.html { redirect_to @res_allocation, notice: 'Res allocation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @res_allocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /res_allocations/1
  # DELETE /res_allocations/1.json
  def destroy
    @res_allocation = ResAllocation.find(params[:id])
    @res_allocation.destroy

    respond_to do |format|
      format.html { redirect_to res_allocations_url }
      format.json { head :no_content }
    end
  end
  
  
  def get_projects
     projects = Project.where("title LIKE :search",search: "%#{params[:q]}%")
     project_titles=""
     unless projects.blank?
        projects.each do |project|
          project_titles+="#{project.title}|#{project.id.to_s}\n"
        end
       render :text=> project_titles
     else
      render :text=> "Not Found"
    end  
  end 
  def get_resources
     resources = Resource.where("name LIKE :search",search: "%#{params[:q]}%")
     resource_names=""
     unless resources.blank?
        resources.each do |resource|
          resource_names+="#{resource.name}|#{resource.id.to_s}\n"
        end
       render :text=> resource_names
     else
      render :text=> "Not Found"
    end  
  end
end

app/helpers/res_allocations_helper.rb
module ResAllocationsHelper
end

app/views/res_allocations/_form (copy).html.erb
<%= form_for(@res_allocation) do |f| %>
  <% if @res_allocation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@res_allocation.errors.count, "error") %> prohibited this res_allocation from being saved:</h2>

      <ul>
      <% @res_allocation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :project %><br />
    <%= f.text_field :project %>
  </div>
  <div class="field">
    <%= f.label :resource %><br />
    <%= f.text_field :resource %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :hours %><br />
    <%= f.time_select :hours %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/res_allocations/_form.html.erb
<%= javascript_include_tag "jquery.min","jquery.autocomplete"%>
<%= stylesheet_link_tag "jquery.autocomplete"%>
<script type="text/javascript">  
  $(document).ready(function() {
    $("#project_title").autocomplete("<%=get_projects_path%>", {
      width: 275,
      matchContains: true,
      selectFirst: false
    });
    $("#project_title").result(function(event, data, formatted) {
       if(data[0]!="Not Found"){
         $("#project_title").val(data[0]);
         $("#res_allocation_project_id").val(data[1]);
       }
       else
         $("#project_title").val("");
    });
    $("#resource_name").autocomplete("<%=get_resources_path%>", {
      width: 275,
      matchContains: true,
      selectFirst: false
    });
    $("#resource_name").result(function(event, data, formatted) {
       if(data[0]!="Not Found"){
         $("#resource_name").val(data[0]);
         $("#res_allocation_resource_id").val(data[1]);
       }
       else
         $("#resource_name").val("");
    });
  });

</script>

<h2>Date: <%=@allocation_date.value.strftime("%m-%d-%Y")%></h2>
<%= form_for @res_allocation, :html => { :class => 'form-horizontal' } do |f| %>
<!--  <div class="control-group">-->
<!--    <%#= f.label :date_id, :class => 'control-label' %>-->
<!--    <div class="controls">-->
      <%= f.hidden_field :allocation_date_id, :value=>@allocation_date.id , :class => 'number_field' %>
<!--    </div>-->
<!--  </div>-->
 <table class="table table-striped table-bordered" id="search_fields" >
    <tr>	 
       <td>
           <%= f.select :project_id, Project.all.map {|p| [p.title, p.id] }, {:include_blank => '- Select Project -'}, :required => true %>
           <%#= text_field_tag :project_title,'', :autocomplete =>"on",  :placeholder => 'Projects'%>  
           <%#=f.hidden_field :project_id%>     
       </td>
         <td>
          
           <%= f.select :resource_id, Resource.all.map {|r| [r.name, r.id] }, {:include_blank => '- Select Resource -'}, :required => true %>
           <%#= text_field_tag :resource_name,'', :autocomplete =>"on",  :placeholder => 'Resources'%>  
           <%#=f.hidden_field :resource_id%>     
        </td>
        <td>
				  <%= f.time_select :hours, :class => 'time_select' %>
         </td>
     </tr> 
     <tr>
      <td colspan="3" style="text-align:center">
        <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                res_allocations_path, :class => 'btn' %>
      </td>
     </tr>
  </table>
<% end %>

app/views/res_allocations/edit.html.erb
<%- model_class = ResAllocation -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/res_allocations/index.html.erb
<%- model_class = ResAllocation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:project) %></th>
      <th><%= model_class.human_attribute_name(:resource) %></th>
      <th><%= model_class.human_attribute_name(:hours) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @res_allocations.each do |res_allocation| %>
      <tr>
        <td><%= res_allocation.project.title %></td>
        <td><%= res_allocation.resource.name %></td>
        <td><%= res_allocation.hours.strftime("%Hhr %Mmin") %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_res_allocation_path(res_allocation), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      res_allocation_path(res_allocation),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_res_allocation_path,
            :class => 'btn btn-primary' %>

app/views/res_allocations/new.html.erb
<%- model_class = ResAllocation -%>
<div class="page-header">
  <h1>Allocate Resource<%#=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/res_allocations/show.html.erb
<%- model_class = ResAllocation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
<!--  <dt><strong><%#= model_class.human_attribute_name(:date) %>:</strong></dt>-->
<!--  <dd><%#= @res_allocation.date_id %></dd>-->
  <dt><strong><%= model_class.human_attribute_name(:project) %>:</strong></dt>
  <dd><%= @res_allocation.project.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:resource) %>:</strong></dt>
  <dd><%= @res_allocation.resource.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hours) %>:</strong></dt>
  <dd><%= @res_allocation.hours %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              res_allocations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_res_allocation_path(@res_allocation), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              res_allocation_path(@res_allocation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>