config/routes.rb
ResourceAllocation::Application.routes.draw do
  resources :technologies

  root to: "projects#index"
  resources :res_allocations
  resources :allocation_dates

  resources :projects 

  resources :resources
  match 'get_projects' => 'res_allocations#get_projects'
  match 'get_resources' => 'res_allocations#get_resources'
  match 'tags_autocomplete' => 'application#tags'
  match 'manage_tag' => 'projects#manage_tag'

end

app/views/resources/_form (copy).html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/_form.html.erb
<%= form_for @resource, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  
<!--  <div class="control-group">-->
<!--    <%#= f.label :position, :class => 'control-label' %>-->
<!--    <div class="controls">-->
<!--      <%#= f.text_field :position, :class => 'text_field' %>-->
<!--    </div>-->
<!--  </div>-->

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                resources_path, :class => 'btn' %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<%- model_class = Resource -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/resources/index.html.erb
<%- model_class = Resource -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
<!--      <th><%#= model_class.human_attribute_name(:position) %></th>-->
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= link_to resource.id, resource_path(resource) %></td>
        <td><%= resource.name %></td>
<!--        <td><%#= resource.position %></td>-->
        <td><%=l resource.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_resource_path(resource), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      resource_path(resource),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_resource_path,
            :class => 'btn btn-primary' %>

app/views/resources/new.html.erb
<%- model_class = Resource -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/resources/show.html.erb
<%- model_class = Resource -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @resource.name %></dd>
<!--  <dt><strong><%#= model_class.human_attribute_name(:position) %>:</strong></dt>-->
<!--  <dd><%#= @resource.position %></dd>-->
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              resources_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_resource_path(@resource), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              resource_path(@resource),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>