config/routes.rb
ResourceAllocation::Application.routes.draw do
  resources :technologies

  root to: "projects#index"
  resources :res_allocations
  resources :allocation_dates

  resources :projects 

  resources :resources
  match 'get_projects' => 'res_allocations#get_projects'
  match 'get_resources' => 'res_allocations#get_resources'
  match 'tags_autocomplete' => 'application#tags'
  match 'manage_tag' => 'projects#manage_tag'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ResourceAllocation" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%=link_to "ResourceAllocation", allocation_dates_path(), :class=>"brand"%>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Projects", projects_path  %></li>
              <li><%= link_to "Resources", resources_path  %></li>
              <li><%= link_to "ResourceAllocation",  new_allocation_date_path  %></li>
              <li><%= link_to "Technology",  technologies_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
<!--        <div class="span3">-->
<!--          <div class="well sidebar-nav">-->
<!--            <ul class="nav nav-list">-->
<!--              <li class="nav-header">Menu</li>-->
<!--              <li><%= link_to "Projects", projects_path()  %></li>-->
<!--              <li><%= link_to "Resources", resources_path()  %></li>-->
<!--              <li><%= link_to "ResourceAllocation", res_allocations_path()  %></li>-->
<!--            </ul>-->
<!--          </div>--><!--/.well -->
<!--        </div>--><!--/span-->
<!--        <div class="span9">-->
        <div	>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>